name: cicd

on:
  push:
    branches:
      - main

env:
  app_version: "1.0.0"

jobs:
  build:
    strategy:
      matrix:
        os:
          - windows-2019
          - windows-2022
        include:
          - platform: ltsc-2019
            os: windows-2019
          - platform: ltsc-2022
            os: windows-2022

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Docker login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker build and push
        run: |
          dir env:
          #$platform = "${{ matrix.os }}"
          #$parent_image = "mcr.microsoft.com/dotnet/aspnet:8.0-windowsservercore-$platform"
          #$tag = "ghcr.io/pbering/dotnet-aspire-dashboard-windows:$env:app_version-$platform"
          #docker build --build-arg PARENT_IMAGE=$parent_image --tag $tag .
          #docker push $tag
